### ISSUE TITLE
validate_response.py:149: KeyError: 'type'

### ISSUE THREAD

**Issue by kids300** [sondrelg/django-swagger-tester#30]
validate_response.py:149: KeyError: 'type'

at `validate_response.py(149)_list()`:
local variable 
- `schema`: `{'type': 'array', 'items': {'$ref': '#/definitions/{my_serializer}'}}`

The schema is defined by paginator: https://github.com/axnsan12/drf-yasg/blob/master/src/drf_yasg/inspectors/query.py#L65

**Comment by sondrelg** [comment]
The current pypi-version was pushed with (fixed in PR #29) bugs, and I have not yet pushed a fixed version. Could you try to install with `pip install git+https://github.com/sondrelg/django-swagger-tester` to verify that the bug still occurs?

The package is also not really ready for production yet. I would estimate that I could refactor and push 1.0 in a week or so.

**Comment by kids300** [comment]
I reinstalled and the bug still occurs.

**Comment by sondrelg** [comment]
Can you run this in `manage.py shell`, and share your schema?

```python
from drf_yasg.openapi import Info
from drf_yasg.generators import OpenAPISchemaGenerator
from json import loads, dumps

schema = OpenAPISchemaGenerator(info=Info(title='', default_version='')).get_schema()
schema = loads(dumps(schema.as_odict()['paths']))  # Converts OrderedDict to dict
```

Feel free to anonymize the data, or just share the section you feel is applicable, I just need some data to test against.

**Comment by sondrelg** [comment]
I will try and work this in as a new feature over the weekend, then release a new version before closing this issue.

Looks like we just need to find the referenced section, for all `ref`s, and check those in place of the section itself.

https://swagger.io/docs/specification/using-ref/

**Comment by sondrelg** [comment]
@kids300

I've not been able to replicate your problem, but I've added some logic to handle references, in #38. 

Can you test this again, using the current test-pypi version? `pip install -i https://test.pypi.org/simple/ django-swagger-tester==0.2.3`

If this doesn't completely resolve the problem (which is a possibility), I would appreciate it if you were able to share your entire schema section, so I can create more rigorous tests. To do this, you could run this:

```pyhon
from drf_yasg.openapi import Info
from drf_yasg.generators import OpenAPISchemaGenerator
from json import loads, dumps

# Get schema as dict
schema = OpenAPISchemaGenerator(info=Info(title='', default_version='')).get_schema()
schema = loads(dumps(schema.as_odict())) 

# Write to file
with open('dump.json', 'w') as f:
    f.write(dumps(schema))
```

**Comment by sondrelg** [comment]
Closing this as I suspect it has been resolved. Please reopen if this turns out not to be the case.
